"""add interview tables

Revision ID: 4c366296a172
Revises: 20260923_coding_invite_recording_path
Create Date: 2026-09-28 13:41:07.974979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '4c366296a172'
down_revision = '20260923_coding_invite_recording_path'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'interview_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('job_id', sa.Integer(), nullable=False),
        sa.Column('candidate_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='interview_session_status'), nullable=False),
        sa.Column('overall_score', sa.Float(), nullable=True),
        sa.Column('recording_path', sa.String(), nullable=True),
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['candidate_id'], ['users.id']),
        sa.ForeignKeyConstraint(['job_id'], ['jobs.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('token'),
    )
    op.create_index('ix_interview_sessions_candidate_id', 'interview_sessions', ['candidate_id'], unique=False)
    op.create_index('ix_interview_sessions_id', 'interview_sessions', ['id'], unique=False)
    op.create_index('ix_interview_sessions_job_id', 'interview_sessions', ['job_id'], unique=False)
    op.create_table(
        'interview_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('answer_transcript', sa.Text(), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('evaluation_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('ix_interview_questions_id', 'interview_questions', ['id'], unique=False)
    op.create_index('ix_interview_questions_session_id', 'interview_questions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interview_questions_session_id', table_name='interview_questions')
    op.drop_index('ix_interview_questions_id', table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index('ix_interview_sessions_job_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_id', table_name='interview_sessions')
    op.drop_index('ix_interview_sessions_candidate_id', table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###
