"""add coding assessment tables

Revision ID: 782d7c6bdfbb
Revises: 20260813_resume_screening
Create Date: 2026-09-06 19:45:49.694798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '782d7c6bdfbb'
down_revision = '20260813_resume_screening'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    coding_question_difficulty = postgresql.ENUM(
        "easy",
        "medium",
        "hard",
        name="coding_question_difficulty",
        create_type=False,
    )
    coding_test_invite_status = postgresql.ENUM(
        "not_started",
        "in_progress",
        "completed",
        name="coding_test_invite_status",
        create_type=False,
    )
    coding_submission_status = postgresql.ENUM(
        "accepted",
        "wrong_answer",
        "runtime_error",
        "time_limit_exceeded",
        "pending",
        name="coding_submission_status",
        create_type=False,
    )
    coding_question_difficulty.create(op.get_bind(), checkfirst=True)
    coding_test_invite_status.create(op.get_bind(), checkfirst=True)
    coding_submission_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "coding_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("difficulty", coding_question_difficulty, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("starter_code", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coding_questions_id"), "coding_questions", ["id"], unique=False)
    op.create_index(op.f("ix_coding_questions_job_id"), "coding_questions", ["job_id"], unique=False)

    op.create_table(
        "coding_tests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coding_tests_id"), "coding_tests", ["id"], unique=False)
    op.create_index(op.f("ix_coding_tests_job_id"), "coding_tests", ["job_id"], unique=False)

    op.create_table(
        "test_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("expected_output", sa.Text(), nullable=False),
        sa.Column("is_sample", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["coding_questions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_test_cases_id"), "test_cases", ["id"], unique=False)
    op.create_index(op.f("ix_test_cases_question_id"), "test_cases", ["question_id"], unique=False)

    op.create_table(
        "coding_test_questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coding_test_id", sa.Integer(), nullable=False),
        sa.Column("coding_question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["coding_question_id"], ["coding_questions.id"]),
        sa.ForeignKeyConstraint(["coding_test_id"], ["coding_tests.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coding_test_questions_id"), "coding_test_questions", ["id"], unique=False)
    op.create_index(op.f("ix_coding_test_questions_coding_test_id"), "coding_test_questions", ["coding_test_id"], unique=False)
    op.create_index(op.f("ix_coding_test_questions_coding_question_id"), "coding_test_questions", ["coding_question_id"], unique=False)

    op.create_table(
        "coding_test_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coding_test_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("status", coding_test_invite_status, nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["candidate_id"], ["users.id"]),
        sa.ForeignKeyConstraint(["coding_test_id"], ["coding_tests.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_coding_test_invites_id"), "coding_test_invites", ["id"], unique=False)
    op.create_index(op.f("ix_coding_test_invites_coding_test_id"), "coding_test_invites", ["coding_test_id"], unique=False)
    op.create_index(op.f("ix_coding_test_invites_candidate_id"), "coding_test_invites", ["candidate_id"], unique=False)

    op.create_table(
        "coding_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invite_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("status", coding_submission_status, nullable=False),
        sa.Column("passed_cases", sa.Integer(), nullable=False),
        sa.Column("total_cases", sa.Integer(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["invite_id"], ["coding_test_invites.id"]),
        sa.ForeignKeyConstraint(["question_id"], ["coding_questions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_coding_submissions_id"), "coding_submissions", ["id"], unique=False)
    op.create_index(op.f("ix_coding_submissions_invite_id"), "coding_submissions", ["invite_id"], unique=False)
    op.create_index(op.f("ix_coding_submissions_question_id"), "coding_submissions", ["question_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_coding_submissions_question_id"), table_name="coding_submissions")
    op.drop_index(op.f("ix_coding_submissions_invite_id"), table_name="coding_submissions")
    op.drop_index(op.f("ix_coding_submissions_id"), table_name="coding_submissions")
    op.drop_table("coding_submissions")
    op.drop_index(op.f("ix_coding_test_invites_candidate_id"), table_name="coding_test_invites")
    op.drop_index(op.f("ix_coding_test_invites_coding_test_id"), table_name="coding_test_invites")
    op.drop_index(op.f("ix_coding_test_invites_id"), table_name="coding_test_invites")
    op.drop_table("coding_test_invites")
    op.drop_index(op.f("ix_coding_test_questions_coding_question_id"), table_name="coding_test_questions")
    op.drop_index(op.f("ix_coding_test_questions_coding_test_id"), table_name="coding_test_questions")
    op.drop_index(op.f("ix_coding_test_questions_id"), table_name="coding_test_questions")
    op.drop_table("coding_test_questions")
    op.drop_index(op.f("ix_test_cases_question_id"), table_name="test_cases")
    op.drop_index(op.f("ix_test_cases_id"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index(op.f("ix_coding_tests_job_id"), table_name="coding_tests")
    op.drop_index(op.f("ix_coding_tests_id"), table_name="coding_tests")
    op.drop_table("coding_tests")
    op.drop_index(op.f("ix_coding_questions_job_id"), table_name="coding_questions")
    op.drop_index(op.f("ix_coding_questions_id"), table_name="coding_questions")
    op.drop_table("coding_questions")
    postgresql.ENUM(name="coding_submission_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="coding_test_invite_status").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="coding_question_difficulty").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
